image: node:9.11.1

build_and_upload:
  script:
    - apt update -y && apt install lftp -y
    - yarn install
    - yarn patch-package
    - yarn build
    - lftp -e "set ftp:ssl-allow no; rm -rf ./public; mirror -R ./public ./; quit" -u $upUser,$upPass $upHost
  only:
    - master
